

import { M_PLUS_1_Code } from 'next/font/google';
import './globals.css';

import { Suspense } from 'react';
import Loading from './loading';
import Navigation from '../components/Navigation';
import Footer from '../components/Footer';

const m_PLUS_1_Code = M_PLUS_1_Code({ subsets: ['latin'] });

export const metadata = {
  title: 'Profile-Site',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className={m_PLUS_1_Code.className}>
        <Suspense fallback={<Loading />}>
          <Navigation />
          {children}
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
